### ISSUE TITLE
All textboxes are greyed out

### ISSUE THREAD

**Issue by andrewducker** [Cito/Pinboard-Pin#10]
Since installing the latest version (0.2.3) the textboxes are all greyed out when trying to add a pin.

![image](https://user-images.githubusercontent.com/91378/34342586-6ed24464-e9ac-11e7-8499-a2be9ff19562.png)

It was working with the previous version (earlier today), and I haven't changed anything.  I tried restarting Firefox to see if that would make a difference, but sadly not.

**Comment by Cito** [comment]
Thanks for reporting this. The last update 0.2.3 had a bug that prevented saving new links. Just published another update 0.2.4 that should fix this.

**Comment by RichardDavies** [comment]
I'm experiencing this same issue with v0.2.7. 
![image 2019-01-28 at 4 13 43 pm](https://user-images.githubusercontent.com/13959/51874954-dff36100-2317-11e9-9c88-3b10ee151a58.png)

**Comment by Cito** [comment]
@RichardDavies Can you check if this is permanent? It can also happen when the Pinboard API is down, which unfortunately happens from time to time. Currently it's working for me (with 0.2.7).

**Comment by RichardDavies** [comment]
Yes, it's working again now so must have just been an API issue. I had a feeling that might have been the case, but I didn't know how to check if the API was working or not and everything on the actual site seemed to still be functional.
