### ISSUE TITLE
Turn off automatic fill of description

### ISSUE THREAD

**Issue by ToasterFaerie** [Cito/Pinboard-Pin#11]
Would it be possible to have an option to turn off the automatic filling of the description field? I would prefer it to be blank, unless I enter it myself, and this is the default behavior of most Pinboard add-ons.

I do like the ability to fill the description if text is highlighted and also the option to automatically use blockquotes.

Thanks for your work! Easily my favorite of the Pinboard add-ons.

**Comment by Cito** [comment]
Thanks for the feedback. I'll consider it for the next update.

**Comment by Cito** [comment]
This can now be configured in version 0.2.6 of Pinboard Pin. You need to uncheck "Use meta elements for description and tags" and check "Use selected text as description" in settings.

**Comment by ToasterFaerie** [comment]
Thanks!
