### ISSUE TITLE
Tags are not being saved

### ISSUE THREAD

**Issue by ToasterFaerie** [Cito/Pinboard-Pin#13]
I just noticed that my bookmarks have been saving without the tags I set. Based on my history this started happening between 4 - 7 days ago. so possibly since the last Firefox update. I do not use Tab containers or Conex as mentioned by #12. I'm using FFx 59.0.1 64bit Windows 10. Let me know if there is more info I can provide.

**Comment by Cito** [comment]
Thanks for reporting this, I can confirm that it worked 4 days ago and now it doesn't, probably because I also upgraded to FF 59.0.1. Will try to fix it this weekend.

**Comment by Cito** [comment]
Am looking into it now, but currently it works. I assume it was a glitch with the Pinboard service rather than a Firefox issue. Can you check again as well?

**Comment by ToasterFaerie** [comment]
Huh, it's working again for me now. Thanks for looking in to it anyway.
