### ISSUE TITLE
Unable to bookmark page due to description too long

### ISSUE THREAD

**Issue by jabbrwcky** [Cito/Pinboard-Pin#15]
I tried to bookmark this page: https://www.elektormagazine.de/labs/how-connect-esp32-to-wpawpa2-enterprise-network and got the response that the bookmark could not be saved.

It worked after deleting the (very long) description extracted from the page.

Maybe the extension should truncate descriptions that are too long or at least come up with a more descriptive error.

**Comment by Cito** [comment]
Thank you for the feedback. Will look into that later.

**Comment by Cito** [comment]
Fix will be relased in version 0.3.0 finally.
