### ISSUE TITLE
'+' characters are removed from tags when saving a page

### ISSUE THREAD

**Issue by davidag** [Cito/Pinboard-Pin#17]
When saving a page (new or existing), plus (+) characters are removed from tags. I've come across this problem because I usually save `c++` tagged pages, which end up being `c` tagged.

This doesn't happen with minus (-), asterisk (*) or slash (/) characters, for example.

Tested with Firefox 69.0.

**Comment by Cito** [comment]
Thanks for reporting this issue, @davidag. I could reproduce it and found that it is caused by a [bug in Angular](https://github.com/angular/angular/issues/18261) for which I will need to add a workaround.

**Comment by Cito** [comment]
Should be fixed now in v0.2.8.

**Comment by davidag** [comment]
Thank you @Cito! Great work!
