### ISSUE TITLE
Can't add websites with Content Security Policy headers

### ISSUE THREAD

**Issue by dannysu** [Cito/Pinboard-Pin#2]
For example, trying to add https://addons.mozilla.org/en-US/firefox/addon/pinboard-pin/ would fail.

Firefox Addons website has [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), which I suspect is preventing the `js/content.js` file from running within the website context.

**Comment by Cito** [comment]
Thanks for reporting this. The script tries to sniff the title and description from the tab content which fails for such protected pages. In this case we should probably fall back to getting the `url` and the `title` from `tabs.getCurrent()` and leave the description empty. Will fix this in the next revision.

**Comment by Cito** [comment]
This has been implemented and will be available in the upcoming version 0.1.5.
