### ISSUE TITLE
I noticed I can't bookmark this link weirdly enough no matter what I try

### ISSUE THREAD

**Issue by ng4ever** [Cito/Pinboard-Pin#20]
https://old.reddit.com/r/jailbreak/comments/di151w/discussion_ive_been_jailbreak_for_nearly_5_months/

Can you test it? 

Maybe it is just my computer/browser settings.

**Comment by Cito** [comment]
It works for me. Have you tried with the latest version 0.2.9 of Pinboard-Pin?

**Comment by Cito** [comment]
Please reopen if the problem still exists in the soon to be released version 0.3.0.
