### ISSUE TITLE
Improve readibility of buttons

### ISSUE THREAD

**Issue by ToasterFaerie** [Cito/Pinboard-Pin#25]
I love the new look of the extension, definitely looks much better. However, I find the text on the upper set of buttons difficult to read. Is it possible to use icons instead of text for these buttons?

**Comment by Cito** [comment]
Maybe a different font or font size can also help, or maybe we can make two rows of buttons. PRs are welcome.

**Comment by Cito** [comment]
This has now been improved in v0.4.0.
