### ISSUE TITLE
Is it possible to hide the 'popular' tags?

### ISSUE THREAD

**Issue by lostfictions** [Cito/Pinboard-Pin#26]
Hi, thanks for this extension! It's been really useful. I've been wondering whether it's possible to hide the "popular" tag category? They're always completely irrelevant, baffling noise and I don't think I've ever clicked on one. For example, the suggestions that come up for the page I'm currently on as I author this issue:
 
![Screenshot from 2020-08-24 07-34-22](https://user-images.githubusercontent.com/567041/91040464-4ddb3980-e5dc-11ea-8219-d35d0ea28399.png)

"1960s", "twitter" multiple times, some random person's twitter handle (is this their way of spamming everyone to try to get more followers?), "ifttt" (presumably a popular method of automating bookmark saving that nobody has ever manually added to a pin), etc...

The extension I previously used didn't show this stuff -- would it be possible to add an option to hide them?

**Comment by Cito** [comment]
This has been implemented in v0.4.0.

**Comment by lostfictions** [comment]
@Cito works great! thank you so much!
