### ISSUE TITLE
Two minor improvements

### ISSUE THREAD

**Issue by WolfgangWeber** [Cito/Pinboard-Pin#4]
Thanks a lot for this nice Firefox add-on!

May I suggest two minor improvements to make this add-on even better?

- When clicking the Pinboard button, would it be possible to automatically focus the tags field? It would save one click when you could start to fill in the desired tags for the new bookmark immediately.

- Furthermore it would also be great when the suggested tags would not be case-sensitive. (For example: When I start typing "wor" the tag "WordPress" will not be suggested.)

Thanks again and kind regards
Wolfgang Weber

**Comment by Cito** [comment]
Good suggestions. I wanted to release an update soon anyway, and will try to get these in.

**Comment by Cito** [comment]
Both ideas have been implemented and will be available in the upcoming version 0.1.5.
