### ISSUE TITLE
Error: Cannot check this page on Pinboard

### ISSUE THREAD

**Issue by obilodeau** [Cito/Pinboard-Pin#42]
Extension no longer works.

![image](https://github.com/user-attachments/assets/8f039590-91ba-4841-a4ff-e320df1932d5)

At first I thought it was on pinboard.in's side but I can use pinboard.in.

Sorry for the poor quality screenshot. My desktop screenshot tool is catching the modal as it is fading away...

**Comment by Cito** [comment]
Is this only for a particular URL or for all?

Sometimes the service API is unresponsive. But it is currently working for me just fine. Can you try again?

**Comment by Cito** [comment]
Now it's flaky for me as well. Anyway this is not an issue of this extension, but the service. You need to contact their support in that case. I have done that now already.

**Comment by DavidSchargel** [comment]
I am experiencing this as well. What do you suggest I tell their support folks?

**Comment by Cito** [comment]
Just point out that the Pinboard API (https://api.pinboard.in/) is unavailable or has performance issues.

Today it was first workign for me again for some time, but currently it is failing again.

**Comment by obilodeau** [comment]
I wrote this morning, I received no reply but it worked all day. Closing.

**Comment by DavidSchargel** [comment]
Email reply just now from pinboard.in...

Thanks for the heads-up about this. I moved the API to a different server thinking I would improve performance, and instead made it worse. I've reverted the change this morning and hopefully things will improve.
