### ISSUE TITLE
Tag autocomplete not working

### ISSUE THREAD

**Issue by andrewducker** [Cito/Pinboard-Pin#43]
Tags are no longer giving me a dropdown autocomplete.

![image](https://github.com/user-attachments/assets/d5b2da01-0eee-4e52-a651-0f5a5d064d03)

Up until now I've had it happily popping up a selection of words that match the tags you've started typing in.

**Comment by Cito** [comment]
I experienced the same sporadically. It's not an issue of this plugin, but of the API service provided by Pinboard. Please contact the Pinboard support in such cases.

**Comment by andrewducker** [comment]
Can you tell me which service it is that is down when this happens?  That way I can let Maciej know which server has fallen over.

**Comment by Cito** [comment]
There is only one API service, at https://api.pinboard.in/v1, he should know.

**Comment by andrewducker** [comment]
Aha!  https://api.pinboard.in/v1/tags/get is returning the tag name in the count field.

There's a big banner on the site right now:
![image](https://github.com/user-attachments/assets/17c4cf24-beb4-4c70-8af9-3d1650d6dec0)
So I've reported it.

**Comment by Cito** [comment]
Thanks @andrewducker. Looks like Maciej was trying to solve some performance issues and accidentally broke the API.
