### ISSUE TITLE
ER: Tab sets

### ISSUE THREAD

**Issue by emory** [Cito/Pinboard-Pin#7]
ER: Add an option for saving all open tabs in a window as a *Tab Set* in Pinboard. Then add support for opening or referencing saved *Tab Set* from Pinboard.

**Comment by Cito** [comment]
Thanks for the suggestion, I'll consider this for the next update - but have to check if and how this is possible, since tab sets are not directly supported by the Pinboard API.

**Comment by Cito** [comment]
Ok, I have now implemented this feature in e6be707 similarly to the original add-on, without using the Pinboard API. You can check it out in the [current version](https://addons.mozilla.org/addon/pinboard-pin/) 0.2.2.
